### PR TITLE
Just more styling added to grid, header & added a 'add to basket' button

### PR DESCRIPTION
**Pull request by asjoss**

### CODE REVIEW

**Review by KerryCX — COMMENTED** [review]
Hello Aaron, it looks good. Liking the look of the cards when you hover over them and click on the button. 
Regards the conflicts, I think just going over the notes to remind yourself of how to resolve. Looks like it is just where lines of code have been moved around and should be easily resolved.

**Comment by Callum-Xavi** [comment]
Hi, I will try looking at resolving the conflicts maybe tonight or tmr? Let me know what you both think.

**Review by Callum-Xavi — DISMISSED** [review]
Let me know if you want me or yourself to make the changes Aaron :)

**Comment by asjoss** [comment]
thanks Callum and Kerry; I'll let you go ahead and make the changes as I don't want to mess anything up further lol

**Comment by KerryCX** [comment]
You won't. This is not truly a conflict. You just need to cut out the old code that is no longer needed.
We need not fear messing up, it is good experience for how to
Fix it.

**Comment by KerryCX** [comment]
Remember the example Lucia did with us adding our lines of code to say something about ourselves. It was not truly a bug but Git needed to know what to do with the lines trying to get in the same place.

**Comment by asjoss** [comment]
I removed old code in the web editor of Git so gonna go ahead n merge :)

**Pull request merged**
