### PR TITLE
favicon change and tab text

### PR DESCRIPTION
**Pull request by KerryCX**
Converted the movies.svg to a favicon and replaced the react-app favicon with this one. Changed text to name of the site.

### CODE REVIEW

**Comment by Callum-Xavi** [comment]
Looks good to me. Feel free to merge :)

**Review by Callum-Xavi — APPROVED** [review]
Looks good to me. Feel free to merge :)

**Comment by asjoss** [comment]
Also looks good to me, merge away :)

**Review by asjoss — APPROVED** [review]
I approve

**Pull request merged**
